import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'ta';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    // General
    "Home": "Home",
    "Scan": "Scan",
    "Schedule": "Schedule",
    "Profile": "Profile",
    "My Plants": "My Plants",
    "Settings": "Settings",
    "Language": "Language",
    "English": "English",
    "Spanish": "Spanish",
    "Tamil": "Tamil",
    "Dark Mode": "Dark Mode",
    "Log Out": "Log Out",
    "Cancel": "Cancel",
    "Save": "Save",
    "See All": "See All",
    "Add Plant": "Add Plant",
    "Search plants...": "Search plants...",
    "Filter": "Filter",
    "Doctor": "Doctor",
    "Explore": "Explore",
    "Care Guide": "Care Guide",
    "Nearby Stores": "Nearby Stores",
    
    // Home
    "Good morning": "Good morning",
    "Good afternoon": "Good afternoon",
    "Good evening": "Good evening",
    "Your plants are looking great today.": "Your plants are looking great today.",
    "Check Plant Health": "Check Plant Health",
    "Scan your plant to get instant AI diagnosis and care tips.": "Scan your plant to get instant AI diagnosis and care tips.",
    "Scan Now": "Scan Now",
    "Today's Tasks": "Today's Tasks",
    "View Schedule": "View Schedule",
    "All caught up!": "All caught up!",
    "No tasks scheduled for today.": "No tasks scheduled for today.",
    
    // Plant Profile
    "Plant Not Found": "Plant Not Found",
    "This plant might have been removed or doesn't exist.": "This plant might have been removed or doesn't exist.",
    "Back to My Plants": "Back to My Plants",
    "Health Score": "Health Score",
    "Mark as Watered": "Mark as Watered",
    "Adjust Schedule": "Adjust Schedule",
    "Weekly Scan": "Weekly Scan",
    "Watering Calendar": "Watering Calendar",
    "Scheduled Water": "Scheduled Water",
    "Watered": "Watered",
    "Needs Scan": "Needs Scan",
    "Care Requirements": "Care Requirements",
    "Care History": "Care History",
    "Water": "Water",
    "Sunlight": "Sunlight",
    "Temp": "Temp",
    "Humidity": "Humidity",
    "Every 7-10 days": "Every 7-10 days",
    "How often should": "How often should",
    "be watered?": "be watered?",
    "Every 3 days": "Every 3 days",
    "Once a week (7 days)": "Once a week (7 days)",
    "Every 2 weeks (14 days)": "Every 2 weeks (14 days)",
    "Save Schedule": "Save Schedule",
    "Are you sure you want to delete": "Are you sure you want to delete",
    "Weekly scan completed! Your plant looks healthy.": "Weekly scan completed! Your plant looks healthy.",
    "Adjust Watering Schedule": "Adjust Watering Schedule",
    
    // Scan
    "Plant Scanner": "Plant Scanner",
    "Analyzing Plant...": "Analyzing Plant...",
    "Identifying species and checking health": "Identifying species and checking health",
    "Health": "Health",
    "Diagnosis": "Diagnosis",
    "Recommendation": "Recommendation",
    "Possible Issues": "Possible Issues",
    "Scan Another": "Scan Another",
    "Save to My Plants": "Save to My Plants",
    "Where is this plant located?": "Where is this plant located?",
    "This helps us customize its care schedule based on typical room conditions.": "This helps us customize its care schedule based on typical room conditions.",
    "I agree to take a picture of this plant each week for its routine Health Scan to ensure it stays healthy.": "I agree to take a picture of this plant each week for its routine Health Scan to ensure it stays healthy.",
    "Save Plant": "Save Plant",
    
    // Auth
    "Sign in to your account": "Sign in to your account",
    "Or": "Or",
    "create a new account": "create a new account",
    "Name": "Name",
    "Password": "Password",
    "Sign in": "Sign in",
    "Create a new account": "Create a new account",
    "sign in to your existing account": "sign in to your existing account",
    "Sign up": "Sign up",

    // Stores
    "plant nurseries and garden centers": "plant nurseries and garden centers",
    "No results found.": "No results found.",
    "An error occurred while searching for stores.": "An error occurred while searching for stores.",
    "Find the best plant nurseries and gardening supplies in your area.": "Find the best plant nurseries and gardening supplies in your area.",
    "What are you looking for?": "What are you looking for?",
    "City and State (e.g., Austin, TX)": "City and State (e.g., Austin, TX)",
    "Search Locations": "Search Locations",
    "Searching nearby areas...": "Searching nearby areas...",
    "Locations Found": "Locations Found",
    "Store Location": "Store Location",
    "View on Google Maps": "View on Google Maps",

    // Doctor
    "Hi there! I'm your AI Plant Doctor. How can I help you and your plants today? You can ask me questions or upload a photo of a sick plant.": "Hi there! I'm your AI Plant Doctor. How can I help you and your plants today? You can ask me questions or upload a photo of a sick plant.",
    "What's wrong with this plant and how can I fix it?": "What's wrong with this plant and how can I fix it?",
    "I'm sorry, I couldn't process that request.": "I'm sorry, I couldn't process that request.",
    "I'm having trouble connecting right now. Please try again later.": "I'm having trouble connecting right now. Please try again later.",
    "AI Plant Doctor": "AI Plant Doctor",
    "Online": "Online",
    "Analyzing...": "Analyzing...",
    "Ask about your plants...": "Ask about your plants...",

    // Guide
    "Watering 101": "Watering 101",
    "Learn the soak and dry method": "Learn the soak and dry method",
    "Lighting Basics": "Lighting Basics",
    "Direct vs indirect light explained": "Direct vs indirect light explained",
    "Pest Control": "Pest Control",
    "Identify and treat common bugs": "Identify and treat common bugs",
    "Soil & Repotting": "Soil & Repotting",
    "Choosing the right mix": "Choosing the right mix",
    "Failed to generate lesson.": "Failed to generate lesson.",
    "An error occurred while generating the lesson. Please try again.": "An error occurred while generating the lesson. Please try again.",
    "Back to Lessons": "Back to Lessons",
    "AI-Generated Lesson": "AI-Generated Lesson",
    "Generating your personalized lesson...": "Generating your personalized lesson...",
    "AI Care Lessons": "AI Care Lessons",
    "Generate personalized, interactive lessons on any plant care topic.": "Generate personalized, interactive lessons on any plant care topic.",
    "Custom Lesson": "Custom Lesson",
    "What do you want to learn today?": "What do you want to learn today?",
    "e.g., How to propagate a Monstera...": "e.g., How to propagate a Monstera...",
    "Generate": "Generate",
    "Popular Topics": "Popular Topics",

    // Schedule
    "New Plant": "New Plant",
    "Morning": "Morning",
    "Afternoon": "Afternoon",
    "Watering Schedule": "Watering Schedule",
    "Keep your plants hydrated and happy.": "Keep your plants hydrated and happy.",
    "AI Smart Schedule Active": "AI Smart Schedule Active",
    "Schedules are automatically adjusted based on your local weather, plant type, and recent health scans.": "Schedules are automatically adjusted based on your local weather, plant type, and recent health scans.",
    "Tasks for": "Tasks for",
    "Add Task": "Add Task",
    "Time": "Time",
    "Amount": "Amount",
    "No tasks scheduled for this day.": "No tasks scheduled for this day.",

    // Profile
    "Plants": "Plants",
    "Care Streak": "Care Streak",
    "Scans": "Scans",
    "Achievements": "Achievements",
    "Notifications": "Notifications",
    "Privacy & Security": "Privacy & Security",

    // Days & Schedule
    "Sun": "Sun",
    "Mon": "Mon",
    "Tue": "Tue",
    "Wed": "Wed",
    "Thu": "Thu",
    "Fri": "Fri",
    "Sat": "Sat",
    "Anytime": "Anytime",
    "100ml": "100ml",
    "150ml": "150ml",
    "50ml": "50ml",
    "200ml": "200ml",
    "Take a picture": "Take a picture",
    "Weekly Health Scan": "Weekly Health Scan",
    "Regular watering": "Regular watering",
    "Moderate": "Moderate",
    "Room Temp": "Room Temp",
    "Average": "Average",
    "Tomorrow": "Tomorrow",
    "Today": "Today",
    "Unknown": "Unknown",
    "Living Room": "Living Room",
    "Bedroom": "Bedroom",
    "Office": "Office",
    "Kitchen": "Kitchen",
    "In 3 days": "In 3 days",
    "In 5 days": "In 5 days",
    "Bright indirect": "Bright indirect",
    "Low to bright indirect": "Low to bright indirect",
    "Bright direct": "Bright direct",
    "High (60%+)": "High (60%+)",
    "High": "High",
    "Low": "Low",
    "Fertilized": "Fertilized",
    "Health Scan": "Health Scan",
    "Plant Parent": "Plant Parent",
    "Plant Parent since 2023": "Plant Parent since 2023",
    "Level 5 Botanist": "Level 5 Botanist",
    "Green Thumb": "Green Thumb",
    "Kept 5 plants alive for 3 months": "Kept 5 plants alive for 3 months",
    "Water Boy": "Water Boy",
    "Watered plants on time for 7 days": "Watered plants on time for 7 days",
    "Plant Doctor": "Plant Doctor",
    "Scanned 10 sick plants": "Scanned 10 sick plants",
    "Mark as Completed": "Mark as Completed",
    "Skip": "Skip",
  },
  es: {
    "Home": "Inicio",
    "Scan": "Escanear",
    "Schedule": "Horario",
    "Profile": "Perfil",
    "My Plants": "Mis Plantas",
    "Settings": "Ajustes",
    "Language": "Idioma",
    "English": "Inglés",
    "Spanish": "Español",
    "Tamil": "Tamil",
    "Dark Mode": "Modo Oscuro",
    "Log Out": "Cerrar Sesión",
    "Cancel": "Cancelar",
    "Save": "Guardar",
    "See All": "Ver Todo",
    "Add Plant": "Añadir Planta",
    "Search plants...": "Buscar plantas...",
    "Filter": "Filtrar",
    "Doctor": "Doctor",
    "Explore": "Explorar",
    "Care Guide": "Guía de Cuidado",
    "Nearby Stores": "Tiendas Cercanas",
    
    "Good morning": "Buenos días",
    "Good afternoon": "Buenas tardes",
    "Good evening": "Buenas noches",
    "Your plants are looking great today.": "Tus plantas se ven geniales hoy.",
    "Check Plant Health": "Revisar Salud",
    "Scan your plant to get instant AI diagnosis and care tips.": "Escanea tu planta para obtener un diagnóstico instantáneo y consejos.",
    "Scan Now": "Escanear Ahora",
    "Today's Tasks": "Tareas de Hoy",
    "View Schedule": "Ver Horario",
    "All caught up!": "¡Todo al día!",
    "No tasks scheduled for today.": "No hay tareas programadas para hoy.",
    
    "Plant Not Found": "Planta no encontrada",
    "This plant might have been removed or doesn't exist.": "Esta planta podría haber sido eliminada o no existe.",
    "Back to My Plants": "Volver a Mis Plantas",
    "Health Score": "Puntuación de Salud",
    "Mark as Watered": "Marcar como Regado",
    "Adjust Schedule": "Ajustar Horario",
    "Weekly Scan": "Escaneo Semanal",
    "Watering Calendar": "Calendario de Riego",
    "Scheduled Water": "Riego Programado",
    "Watered": "Regado",
    "Needs Scan": "Necesita Escaneo",
    "Care Requirements": "Requisitos de Cuidado",
    "Care History": "Historial de Cuidado",
    "Water": "Agua",
    "Sunlight": "Luz Solar",
    "Temp": "Temp",
    "Humidity": "Humedad",
    "Every 7-10 days": "Cada 7-10 días",
    "How often should": "¿Con qué frecuencia se debe regar",
    "be watered?": "?",
    "Every 3 days": "Cada 3 días",
    "Once a week (7 days)": "Una vez a la semana (7 días)",
    "Every 2 weeks (14 days)": "Cada 2 semanas (14 días)",
    "Save Schedule": "Guardar Horario",
    "Are you sure you want to delete": "¿Estás seguro de que quieres eliminar",
    "Weekly scan completed! Your plant looks healthy.": "¡Escaneo semanal completado! Tu planta se ve saludable.",
    "Adjust Watering Schedule": "Ajustar Horario de Riego",
    
    "Plant Scanner": "Escáner de Plantas",
    "Analyzing Plant...": "Analizando Planta...",
    "Identifying species and checking health": "Identificando especie y revisando salud",
    "Health": "Salud",
    "Diagnosis": "Diagnóstico",
    "Recommendation": "Recomendación",
    "Possible Issues": "Posibles Problemas",
    "Scan Another": "Escanear Otra",
    "Save to My Plants": "Guardar en Mis Plantas",
    "Where is this plant located?": "¿Dónde está ubicada esta planta?",
    "This helps us customize its care schedule based on typical room conditions.": "Esto nos ayuda a personalizar su horario de cuidado.",
    "I agree to take a picture of this plant each week for its routine Health Scan to ensure it stays healthy.": "Acepto tomar una foto de esta planta cada semana para su Escaneo de Salud.",
    "Save Plant": "Guardar Planta",
    
    "Sign in to your account": "Inicia sesión en tu cuenta",
    "Or": "O",
    "create a new account": "crear una cuenta nueva",
    "Name": "Nombre",
    "Password": "Contraseña",
    "Sign in": "Iniciar sesión",
    "Create a new account": "Crear una cuenta nueva",
    "sign in to your existing account": "inicia sesión en tu cuenta existente",
    "Sign up": "Registrarse",

    "plant nurseries and garden centers": "viveros de plantas y centros de jardinería",
    "No results found.": "No se encontraron resultados.",
    "An error occurred while searching for stores.": "Ocurrió un error al buscar tiendas.",
    "Find the best plant nurseries and gardening supplies in your area.": "Encuentra los mejores viveros y suministros de jardinería en tu área.",
    "What are you looking for?": "¿Qué estás buscando?",
    "City and State (e.g., Austin, TX)": "Ciudad y Estado (ej. Austin, TX)",
    "Search Locations": "Buscar Ubicaciones",
    "Searching nearby areas...": "Buscando áreas cercanas...",
    "Locations Found": "Ubicaciones Encontradas",
    "Store Location": "Ubicación de la Tienda",
    "View on Google Maps": "Ver en Google Maps",

    "Hi there! I'm your AI Plant Doctor. How can I help you and your plants today? You can ask me questions or upload a photo of a sick plant.": "¡Hola! Soy tu Doctor de Plantas IA. ¿Cómo puedo ayudarte a ti y a tus plantas hoy? Puedes hacerme preguntas o subir una foto de una planta enferma.",
    "What's wrong with this plant and how can I fix it?": "¿Qué le pasa a esta planta y cómo puedo arreglarlo?",
    "I'm sorry, I couldn't process that request.": "Lo siento, no pude procesar esa solicitud.",
    "I'm having trouble connecting right now. Please try again later.": "Tengo problemas para conectarme en este momento. Por favor, inténtalo de nuevo más tarde.",
    "AI Plant Doctor": "Doctor de Plantas IA",
    "Online": "En línea",
    "Analyzing...": "Analizando...",
    "Ask about your plants...": "Pregunta sobre tus plantas...",

    "Watering 101": "Riego 101",
    "Learn the soak and dry method": "Aprende el método de remojo y secado",
    "Lighting Basics": "Conceptos Básicos de Iluminación",
    "Direct vs indirect light explained": "Luz directa vs indirecta explicada",
    "Pest Control": "Control de Plagas",
    "Identify and treat common bugs": "Identifica y trata insectos comunes",
    "Soil & Repotting": "Tierra y Trasplante",
    "Choosing the right mix": "Elegir la mezcla adecuada",
    "Failed to generate lesson.": "Error al generar la lección.",
    "An error occurred while generating the lesson. Please try again.": "Ocurrió un error al generar la lección. Por favor, inténtalo de nuevo.",
    "Back to Lessons": "Volver a Lecciones",
    "AI-Generated Lesson": "Lección Generada por IA",
    "Generating your personalized lesson...": "Generando tu lección personalizada...",
    "AI Care Lessons": "Lecciones de Cuidado IA",
    "Generate personalized, interactive lessons on any plant care topic.": "Genera lecciones personalizadas e interactivas sobre cualquier tema de cuidado de plantas.",
    "Custom Lesson": "Lección Personalizada",
    "What do you want to learn today?": "¿Qué quieres aprender hoy?",
    "e.g., How to propagate a Monstera...": "ej. Cómo propagar una Monstera...",
    "Generate": "Generar",
    "Popular Topics": "Temas Populares",

    "New Plant": "Nueva Planta",
    "Morning": "Mañana",
    "Afternoon": "Tarde",
    "Watering Schedule": "Horario de Riego",
    "Keep your plants hydrated and happy.": "Mantén tus plantas hidratadas y felices.",
    "AI Smart Schedule Active": "Horario Inteligente IA Activo",
    "Schedules are automatically adjusted based on your local weather, plant type, and recent health scans.": "Los horarios se ajustan automáticamente según tu clima local, tipo de planta y escaneos de salud recientes.",
    "Tasks for": "Tareas para",
    "Add Task": "Añadir Tarea",
    "Time": "Hora",
    "Amount": "Cantidad",
    "No tasks scheduled for this day.": "No hay tareas programadas para este día.",

    "Plants": "Plantas",
    "Care Streak": "Racha de Cuidado",
    "Scans": "Escaneos",
    "Achievements": "Logros",
    "Notifications": "Notificaciones",
    "Privacy & Security": "Privacidad y Seguridad",

    // Days & Schedule
    "Sun": "Dom",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mié",
    "Thu": "Jue",
    "Fri": "Vie",
    "Sat": "Sáb",
    "Anytime": "En cualquier momento",
    "100ml": "100ml",
    "150ml": "150ml",
    "50ml": "50ml",
    "200ml": "200ml",
    "Take a picture": "Tomar una foto",
    "Weekly Health Scan": "Escaneo de salud semanal",
    "Regular watering": "Riego regular",
    "Moderate": "Moderado",
    "Room Temp": "Temp. Ambiente",
    "Average": "Promedio",
    "Tomorrow": "Mañana",
    "Today": "Hoy",
    "Unknown": "Desconocido",
    "Living Room": "Sala de estar",
    "Bedroom": "Dormitorio",
    "Office": "Oficina",
    "Kitchen": "Cocina",
    "In 3 days": "En 3 días",
    "In 5 days": "En 5 días",
    "Bright indirect": "Luz indirecta brillante",
    "Low to bright indirect": "Luz indirecta baja a brillante",
    "Bright direct": "Luz directa brillante",
    "High (60%+)": "Alta (60%+)",
    "High": "Alta",
    "Low": "Baja",
    "Fertilized": "Fertilizado",
    "Health Scan": "Escaneo de Salud",
    "Plant Parent": "Padre de Plantas",
    "Plant Parent since 2023": "Padre de Plantas desde 2023",
    "Level 5 Botanist": "Botánico Nivel 5",
    "Green Thumb": "Mano Verde",
    "Kept 5 plants alive for 3 months": "Mantuvo 5 plantas vivas por 3 meses",
    "Water Boy": "Chico del Agua",
    "Watered plants on time for 7 days": "Regó las plantas a tiempo por 7 días",
    "Plant Doctor": "Doctor de Plantas",
    "Scanned 10 sick plants": "Escaneó 10 plantas enfermas",
    "Mark as Completed": "Marcar como Completado",
    "Skip": "Omitir",
  },
  ta: {
    "Home": "முகப்பு",
    "Scan": "ஸ்கேன்",
    "Schedule": "அட்டவணை",
    "Profile": "சுயவிவரம்",
    "My Plants": "என் தாவரங்கள்",
    "Settings": "அமைப்புகள்",
    "Language": "மொழி",
    "English": "ஆங்கிலம்",
    "Spanish": "ஸ்பானிஷ்",
    "Tamil": "தமிழ்",
    "Dark Mode": "இருண்ட பயன்முறை",
    "Log Out": "வெளியேறு",
    "Cancel": "ரத்துசெய்",
    "Save": "சேமி",
    "See All": "அனைத்தையும் காண்",
    "Add Plant": "தாவரத்தை சேர்",
    "Search plants...": "தாவரங்களை தேடு...",
    "Filter": "வடிகட்டி",
    "Doctor": "மருத்துவர்",
    "Explore": "ஆராயுங்கள்",
    "Care Guide": "பராமரிப்பு வழிகாட்டி",
    "Nearby Stores": "அருகிலுள்ள கடைகள்",
    
    "Good morning": "காலை வணக்கம்",
    "Good afternoon": "மதிய வணக்கம்",
    "Good evening": "மாலை வணக்கம்",
    "Your plants are looking great today.": "உங்கள் தாவரங்கள் இன்று அருமையாக உள்ளன.",
    "Check Plant Health": "ஆரோக்கியத்தை சரிபார்க்கவும்",
    "Scan your plant to get instant AI diagnosis and care tips.": "உடனடி AI கண்டறிதல் மற்றும் குறிப்புகளைப் பெற ஸ்கேன் செய்யவும்.",
    "Scan Now": "இப்போது ஸ்கேன் செய்",
    "Today's Tasks": "இன்றைய பணிகள்",
    "View Schedule": "அட்டவணையை காண்",
    "All caught up!": "எல்லாம் முடிந்தது!",
    "No tasks scheduled for today.": "இன்று எந்த பணிகளும் இல்லை.",
    
    "Plant Not Found": "தாவரம் கண்டறியப்படவில்லை",
    "This plant might have been removed or doesn't exist.": "இந்த தாவரம் நீக்கப்பட்டிருக்கலாம் அல்லது இல்லை.",
    "Back to My Plants": "என் தாவரங்களுக்குத் திரும்பு",
    "Health Score": "ஆரோக்கிய மதிப்பெண்",
    "Mark as Watered": "நீர் ஊற்றியதாக குறி",
    "Adjust Schedule": "அட்டவணையை மாற்று",
    "Weekly Scan": "வாராந்திர ஸ்கேன்",
    "Watering Calendar": "நீர்ப்பாசன காலண்டர்",
    "Scheduled Water": "திட்டமிடப்பட்ட நீர்",
    "Watered": "நீர் ஊற்றப்பட்டது",
    "Needs Scan": "ஸ்கேன் தேவை",
    "Care Requirements": "பராமரிப்பு தேவைகள்",
    "Care History": "பராமரிப்பு வரலாறு",
    "Water": "நீர்",
    "Sunlight": "சூரிய ஒளி",
    "Temp": "வெப்பநிலை",
    "Humidity": "ஈரப்பதம்",
    "Every 7-10 days": "ஒவ்வொரு 7-10 நாட்களுக்கும்",
    "How often should": "எவ்வளவு அடிக்கடி",
    "be watered?": "நீர் ஊற்ற வேண்டும்?",
    "Every 3 days": "ஒவ்வொரு 3 நாட்களுக்கும்",
    "Once a week (7 days)": "வாரத்திற்கு ஒரு முறை (7 நாட்கள்)",
    "Every 2 weeks (14 days)": "2 வாரங்களுக்கு ஒரு முறை (14 நாட்கள்)",
    "Save Schedule": "அட்டவணையை சேமி",
    "Are you sure you want to delete": "நீங்கள் நிச்சயமாக நீக்க விரும்புகிறீர்களா",
    "Weekly scan completed! Your plant looks healthy.": "வாராந்திர ஸ்கேன் முடிந்தது! உங்கள் தாவரம் ஆரோக்கியமாக உள்ளது.",
    "Adjust Watering Schedule": "நீர்ப்பாசன அட்டவணையை மாற்று",
    
    "Plant Scanner": "தாவர ஸ்கேனர்",
    "Analyzing Plant...": "பகுப்பாய்வு செய்கிறது...",
    "Identifying species and checking health": "இனங்களை அடையாளம் கண்டு ஆரோக்கியத்தை சரிபார்க்கிறது",
    "Health": "ஆரோக்கியம்",
    "Diagnosis": "கண்டறிதல்",
    "Recommendation": "பரிந்துரை",
    "Possible Issues": "சாத்தியமான சிக்கல்கள்",
    "Scan Another": "மற்றொன்றை ஸ்கேன் செய்",
    "Save to My Plants": "என் தாவரங்களில் சேமி",
    "Where is this plant located?": "இந்த தாவரம் எங்கே உள்ளது?",
    "This helps us customize its care schedule based on typical room conditions.": "இது அதன் பராமரிப்பு அட்டவணையைத் தனிப்பயனாக்க உதவுகிறது.",
    "I agree to take a picture of this plant each week for its routine Health Scan to ensure it stays healthy.": "இந்த தாவரத்தின் ஆரோக்கியத்தை உறுதிப்படுத்த ஒவ்வொரு வாரமும் படம் எடுக்க ஒப்புக்கொள்கிறேன்.",
    "Save Plant": "தாவரத்தை சேமி",
    
    "Sign in to your account": "உங்கள் கணக்கில் உள்நுழைக",
    "Or": "அல்லது",
    "create a new account": "புதிய கணக்கை உருவாக்கு",
    "Name": "பெயர்",
    "Password": "கடவுச்சொல்",
    "Sign in": "உள்நுழைக",
    "Create a new account": "புதிய கணக்கை உருவாக்கு",
    "sign in to your existing account": "உங்கள் கணக்கில் உள்நுழைக",
    "Sign up": "பதிவு செய்",

    "plant nurseries and garden centers": "தாவர நாற்றங்கால் மற்றும் தோட்ட மையங்கள்",
    "No results found.": "முடிவுகள் எதுவும் கிடைக்கவில்லை.",
    "An error occurred while searching for stores.": "கடைகளைத் தேடும்போது பிழை ஏற்பட்டது.",
    "Find the best plant nurseries and gardening supplies in your area.": "உங்கள் பகுதியில் சிறந்த தாவர நாற்றங்கால் மற்றும் தோட்டக்கலை பொருட்களைக் கண்டறியவும்.",
    "What are you looking for?": "நீங்கள் எதைத் தேடுகிறீர்கள்?",
    "City and State (e.g., Austin, TX)": "நகரம் மற்றும் மாநிலம் (எ.கா., Austin, TX)",
    "Search Locations": "இடங்களைத் தேடு",
    "Searching nearby areas...": "அருகிலுள்ள பகுதிகளைத் தேடுகிறது...",
    "Locations Found": "இடங்கள் கண்டறியப்பட்டன",
    "Store Location": "கடை இடம்",
    "View on Google Maps": "கூகுள் மேப்ஸில் காண்",

    "Hi there! I'm your AI Plant Doctor. How can I help you and your plants today? You can ask me questions or upload a photo of a sick plant.": "வணக்கம்! நான் உங்கள் AI தாவர மருத்துவர். இன்று உங்களுக்கும் உங்கள் தாவரங்களுக்கும் நான் எவ்வாறு உதவ முடியும்? நீங்கள் என்னிடம் கேள்விகளைக் கேட்கலாம் அல்லது நோய்வாய்ப்பட்ட தாவரத்தின் புகைப்படத்தைப் பதிவேற்றலாம்.",
    "What's wrong with this plant and how can I fix it?": "இந்த தாவரத்திற்கு என்ன பிரச்சனை, அதை நான் எப்படி சரிசெய்வது?",
    "I'm sorry, I couldn't process that request.": "மன்னிக்கவும், அந்த கோரிக்கையை என்னால் செயல்படுத்த முடியவில்லை.",
    "I'm having trouble connecting right now. Please try again later.": "இப்போது இணைப்பதில் சிக்கல் உள்ளது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    "AI Plant Doctor": "AI தாவர மருத்துவர்",
    "Online": "ஆன்லைனில்",
    "Analyzing...": "பகுப்பாய்வு செய்கிறது...",
    "Ask about your plants...": "உங்கள் தாவரங்களைப் பற்றி கேளுங்கள்...",

    "Watering 101": "நீர்ப்பாசனம் 101",
    "Learn the soak and dry method": "ஊறவைத்து உலர்த்தும் முறையைக் கற்றுக்கொள்ளுங்கள்",
    "Lighting Basics": "ஒளியமைப்பு அடிப்படைகள்",
    "Direct vs indirect light explained": "நேரடி மற்றும் மறைமுக ஒளி விளக்கப்பட்டுள்ளது",
    "Pest Control": "பூச்சி கட்டுப்பாடு",
    "Identify and treat common bugs": "பொதுவான பூச்சிகளை அடையாளம் கண்டு சிகிச்சையளிக்கவும்",
    "Soil & Repotting": "மண் மற்றும் மறுசீரமைப்பு",
    "Choosing the right mix": "சரியான கலவையைத் தேர்ந்தெடுப்பது",
    "Failed to generate lesson.": "பாடத்தை உருவாக்க முடியவில்லை.",
    "An error occurred while generating the lesson. Please try again.": "பாடத்தை உருவாக்கும்போது பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    "Back to Lessons": "பாடங்களுக்குத் திரும்பு",
    "AI-Generated Lesson": "AI உருவாக்கிய பாடம்",
    "Generating your personalized lesson...": "உங்கள் தனிப்பயனாக்கப்பட்ட பாடத்தை உருவாக்குகிறது...",
    "AI Care Lessons": "AI பராமரிப்பு பாடங்கள்",
    "Generate personalized, interactive lessons on any plant care topic.": "எந்தவொரு தாவர பராமரிப்பு தலைப்பிலும் தனிப்பயனாக்கப்பட்ட, ஊடாடும் பாடங்களை உருவாக்கவும்.",
    "Custom Lesson": "தனிப்பயன் பாடம்",
    "What do you want to learn today?": "இன்று நீங்கள் என்ன கற்றுக்கொள்ள விரும்புகிறீர்கள்?",
    "e.g., How to propagate a Monstera...": "எ.கா., ஒரு மான்ஸ்டெராவை எவ்வாறு பரப்புவது...",
    "Generate": "உருவாக்கு",
    "Popular Topics": "பிரபலமான தலைப்புகள்",

    "New Plant": "புதிய தாவரம்",
    "Morning": "காலை",
    "Afternoon": "மதியம்",
    "Watering Schedule": "நீர்ப்பாசன அட்டவணை",
    "Keep your plants hydrated and happy.": "உங்கள் தாவரங்களை நீரேற்றமாகவும் மகிழ்ச்சியாகவும் வைத்திருங்கள்.",
    "AI Smart Schedule Active": "AI ஸ்மார்ட் அட்டவணை செயலில் உள்ளது",
    "Schedules are automatically adjusted based on your local weather, plant type, and recent health scans.": "உங்கள் உள்ளூர் வானிலை, தாவர வகை மற்றும் சமீபத்திய சுகாதார ஸ்கேன்களின் அடிப்படையில் அட்டவணைகள் தானாகவே சரிசெய்யப்படும்.",
    "Tasks for": "பணிகள்",
    "Add Task": "பணியைச் சேர்",
    "Time": "நேரம்",
    "Amount": "அளவு",
    "No tasks scheduled for this day.": "இந்த நாளுக்கு எந்த பணிகளும் திட்டமிடப்படவில்லை.",

    "Plants": "தாவரங்கள்",
    "Care Streak": "பராமரிப்பு தொடர்",
    "Scans": "ஸ்கேன்கள்",
    "Achievements": "சாதனைகள்",
    "Notifications": "அறிவிப்புகள்",
    "Privacy & Security": "தனியுரிமை மற்றும் பாதுகாப்பு",

    // Days & Schedule
    "Sun": "ஞாயிறு",
    "Mon": "திங்கள்",
    "Tue": "செவ்வாய்",
    "Wed": "புதன்",
    "Thu": "வியாழன்",
    "Fri": "வெள்ளி",
    "Sat": "சனி",
    "Anytime": "எந்த நேரத்திலும்",
    "100ml": "100மிலி",
    "150ml": "150மிலி",
    "50ml": "50மிலி",
    "200ml": "200மிலி",
    "Take a picture": "படம் எடுக்கவும்",
    "Weekly Health Scan": "வாராந்திர சுகாதார ஸ்கேன்",
    "Regular watering": "வழக்கமான நீர்ப்பாசனம்",
    "Moderate": "மிதமான",
    "Room Temp": "அறை வெப்பநிலை",
    "Average": "சராசரி",
    "Tomorrow": "நாளை",
    "Today": "இன்று",
    "Unknown": "தெரியவில்லை",
    "Living Room": "வாழ்க்கை அறை",
    "Bedroom": "படுக்கையறை",
    "Office": "அலுவலகம்",
    "Kitchen": "சமையலறை",
    "In 3 days": "3 நாட்களில்",
    "In 5 days": "5 நாட்களில்",
    "Bright indirect": "பிரகாசமான மறைமுக ஒளி",
    "Low to bright indirect": "குறைந்த முதல் பிரகாசமான மறைமுக ஒளி",
    "Bright direct": "பிரகாசமான நேரடி ஒளி",
    "High (60%+)": "அதிகம் (60%+)",
    "High": "அதிகம்",
    "Low": "குறைவு",
    "Fertilized": "உரமிடப்பட்டது",
    "Health Scan": "சுகாதார ஸ்கேன்",
    "Plant Parent": "தாவர பெற்றோர்",
    "Plant Parent since 2023": "2023 முதல் தாவர பெற்றோர்",
    "Level 5 Botanist": "நிலை 5 தாவரவியலாளர்",
    "Green Thumb": "பச்சை கட்டைவிரல்",
    "Kept 5 plants alive for 3 months": "5 தாவரங்களை 3 மாதங்கள் உயிருடன் வைத்திருந்தார்",
    "Water Boy": "தண்ணீர் பையன்",
    "Watered plants on time for 7 days": "7 நாட்களுக்கு சரியான நேரத்தில் தாவரங்களுக்கு தண்ணீர் ஊற்றினார்",
    "Plant Doctor": "தாவர மருத்துவர்",
    "Scanned 10 sick plants": "10 நோய்வாய்ப்பட்ட தாவரங்களை ஸ்கேன் செய்தார்",
    "Mark as Completed": "முடிந்தது எனக் குறிக்கவும்",
    "Skip": "தவிர்",
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const storedLang = localStorage.getItem('plant_app_lang') as Language;
    if (storedLang && translations[storedLang]) {
      setLanguageState(storedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('plant_app_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
